### ISSUE TITLE
Hashing algorithm better suited for ARM

### ISSUE THREAD

**Issue by pkolaczk** [pkolaczk/fclones#10]
Add an option to choose a different hash function.
E.g.:

```
fclones --hash highway -R ~
```

**Comment by pkolaczk** [comment]
@yehia2amer - which hashes would you like to try?

**Comment by yehia2amer** [comment]
Actually I tried to scrap the whole internet for anyone who already ran [smhasher](https://github.com/rurban/smhasher) on ARM. but I couldn't find any public resource with this info.
So I tried to do that my own. but I am getting a problem running the code on my machine. So I opened an issue [here](https://github.com/rurban/smhasher/issues/130)
I will still try to fix this problem and get back to you. and please let me know if you know any resources that can help !

**Comment by pkolaczk** [comment]
Selection of hashes addressed by #163
