### ISSUE TITLE
Honor .gitignore or have its own .fcignore

### ISSUE THREAD

**Issue by laoshaw** [pkolaczk/fclones#101]
can fclones ignore known directories such as node_modules, .mypy_cache, CMakefile Release/Debug directories,etc, or let the user to create .flignore file for them.

or, just respect .gitignore by default as fd and rg do.

the best feature I got from rust tools is that it's modern in the sense it is .git etc aware.

**Comment by pkolaczk** [comment]
That would make a nice new feature. For now, you can exclude multiple paths with --exclude.
