### ISSUE TITLE
fclones group --transform flag output not useable by fclones move 

### ISSUE THREAD

**Issue by peddamat** [pkolaczk/fclones#125]
Running the following command, (which compares RAW files using their embedded thumbnail):
```
fclones group --cache --transform 'dcraw -c -e $IN' --format json -o output.json /mnt/photos
```
results in `fclones move` throwing the following:
```
[2022-05-11 15:25:33.626] fclones:  warn: Skipping file '/mnt/h/Photo Archive/2020/2020-08-19/f51562240.raf' with length 56.1 MB different than the group length 2657671
```
As `dcraw -c` outputs to stdout, my thought is that fclones is saving the temp file's filesize, instead of the original file's filesize to the output json.

This causes a subsequent `fclones move` to throw the warning about the filesize mismatch, preventing deduplication.

**Comment by pkolaczk** [comment]
Thanks!
I can see two things wrong here: 

1. as you noted, the size check should not be done if --transform was used

2. it should not allow to use --cached with --transform, because caching is not supported in that case
