### ISSUE TITLE
v0.29.0 clap upgrade to 4.0 results with --help not using colours anymore

### ISSUE THREAD

**Issue by kapitainsky** [pkolaczk/fclones#169]
e.g., `fclones group --help`

v0.28.0 on macOS and Debian:

<img width="896" alt="colours" src="https://user-images.githubusercontent.com/15635386/192198795-df9e8e05-0911-4f11-9345-7fd265ea8388.png">

v0.29.0 - no more colours:

<img width="896" alt="bq" src="https://user-images.githubusercontent.com/15635386/192198858-ed4d1b61-04a4-424c-85d3-c26db9227a49.png">

**Comment by kapitainsky** [comment]
Maybe it is intentional but IMHO colours make `--help` much easier to read.

**Comment by pkolaczk** [comment]
> During clap 3.0.0 development, we were looking at removing AppSettings::ColoredHelp, making it always on. This helped identify several problems with our existing colored help and started a broader re-examination of our --help output. For more background on each decision, I recommend you check out the [parent issue](https://github.com/clap-rs/clap/issues/4132)

> Problems with the colored help
>    The choice of colors was controversial, some liked it but others hated it. We want safe out-of-the-box defaults
>    Some applications have a specific branding to their color choices and clap's colors don't fit within that, so they would rather have none instead


Actually many apps don't use colors in help, but just bold or different shades of gray/white.

**Comment by kapitainsky** [comment]
Thank you for explanation. Fair enough.
