### ISSUE TITLE
Fclones doesnt work well with empty files.

### ISSUE THREAD

**Issue by Anonymous2716** [pkolaczk/fclones#176]
I have a list of directories and a few thousands files in them. My system is Linux and all files are readable + writeable. I was doing some testing with fdupes and fclones. While fclones does the job pretty well and fast for finding duplicate files it doesn't seem to work well with empty files.

I did: 

```
fclones group --hidden --hash-fn sha512 . > a.txt

fclones move dup <a.txt
```
This doesn't move the empty files.

**Comment by kapitainsky** [comment]
```
$ fclones group --help
...
  -s, --min <BYTES>
          Minimum file size in bytes (inclusive).
          Units like KB, KiB, MB, MiB, GB, GiB are supported.
          [default: 1]
...
```

you run it with minimum size 1 (default). Set it to 0
