### ISSUE TITLE
fclone move <target> fails in windows 10

### ISSUE THREAD

**Issue by nvshibu** [pkolaczk/fclones#185]
The target location for move command could not be specified in windows 10. 

Error Messsage is "thread 'thread '<unnamed>thread '' panicked at '<unnamed>assertion failed: path.is_relative()<unnamed>thread '' panicked at '<unnamed>' panicked at '', assertion failed: path.is_relative()src/path.rsassertion failed: path.is_relative()' panicked at '', assertion failed: path.is_relative()'

**Comment by pkolaczk** [comment]
Reproduced
