### ISSUE TITLE
fclones group partially clears the terminal

### ISSUE THREAD

**Issue by th1000s** [pkolaczk/fclones#217]
Running `fclones group .` works fine, but redirecting paints over existing output. In both xterm and konsole the following terminal state

```bash
/foo$ for i in {1..25}; do echo $i; done
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
/foo$ fclones group . > /dev/null
```
becomes this after running the `group` command:

```shell
/foo$ for i in {1..25}; do echo $i; done
1
2
3
/foo$ 
``` 

Redirecting stderr (e.g. `2> /dev/null`) prevents this.

**Comment by Motophan** [comment]
Are you on arch linux?
Mine does that too

**Comment by Pesc0** [comment]
On archlinux can confirm. Also `fclones group | fclones remove --dry-run` results in `fclones: error: Failed to write report: Broken pipe (os error 32)`

**Comment by pkolaczk** [comment]
I guess that might be something related to printing the progress bar. 
Adding `--quiet` option fixes it `fclones --quiet group ... >/dev/null`.

Thank's for reporting.

**Comment by Pesc0** [comment]
@pkolaczk might [this commit](https://github.com/pkolaczk/fclones/commit/2a68ac4deb6dfe91dc619d7c05beecd775159f78) be the cause?

**Comment by pkolaczk** [comment]
I don't know, this indeed looks like `indicatif` issue. I have no idea if downgrading it fixes it. Upgrading to the newest version didn't help.

**Comment by Pesc0** [comment]
Thank you so much Piotr!
