### ISSUE TITLE
Improvement request: preserve metadata of replaced files

### ISSUE THREAD

**Issue by boozook** [pkolaczk/fclones#221]
For example I have two equal files `A` & `B`.
`B` have creation and modification dates.
After `fclones dedupe` dates reseted to current. Instead of it will be better to set dates to original from `B` or maybe from `A`.
Also will be great to preserve other metadata __and filesystem flags__ such as tags or timemachine flags.

**Comment by kapitainsky** [comment]
Can you show an example that it is not preserved? There were some issues with xattr in the past but all was fixed.

**Comment by boozook** [comment]
Seems to my horrible mistake, just tested one more time and dates are correct 🤔, sorry for disturbance.

**Comment by kapitainsky** [comment]
Never enough testing and careful checking:)
