### ISSUE TITLE
ARMv7 32bit assistance

### ISSUE THREAD

**Issue by jpercyasnet** [pkolaczk/fclones#224]
I have raspberry pi 3 B ARMv7 32bit and would like to run fclones on it.
Is there a version for 32bit?
If not, want steps do I need to do to compile it on my raspberry?

**Comment by kapitainsky** [comment]
> I have raspberry pi 3 B ARMv7 32bit and would like to run fclones on it. Is there a version for 32bit? If not, want steps do I need to do to compile it on my raspberry?

It should be as simple as:

1. [Install rust](https://www.rust-lang.org/tools/install) programming language:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Build `fclones` from source (it will take few minutes)
`cargo install fclones`

**Comment by jpercyasnet** [comment]
followed the three steps and it worked!
Thanks!
