### ISSUE TITLE
Change to group progress output in 0.33.0 breaks piping to file via stdout

### ISSUE THREAD

**Issue by javmorin** [pkolaczk/fclones#241]
After update to 0.33.0, when piping the output of `fclones group`  to a file per the examples in the readme (i.e. `$ fclones group . >dupes.txt` the resulting dupes.txt file contains the text during the scanning phases and will not work for input to other `fclones` commands.

Using `fclones group -o dupes.txt` does work as expected.

**Comment by javmorin** [comment]
Sample file showing the issue: [dupes.txt](https://github.com/pkolaczk/fclones/files/13064160/dupes.txt)

**Comment by pkolaczk** [comment]
Good catch! Thanks for a quick report!
Indeed, I messed it up. ;)
