### ISSUE TITLE
fclones depends on libc6:amd64 (>= 2.36)

### ISSUE THREAD

**Issue by KyleSanderson** [pkolaczk/fclones#245]
Unpacking fclones (0.33.1) over (0.32.1) ...
dpkg: dependency problems prevent configuration of fclones:
 fclones depends on libc6:amd64 (>= 2.36); however:
  Version of libc6:amd64 on system is 2.35-0ubuntu3.4.

**Comment by pkolaczk** [comment]
You're likely on a too old Linux. What distro is it?

**Comment by KyleSanderson** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

**Comment by pkolaczk** [comment]
Ok, I'll take a look. Probably the builder image for updated and uses a too new libc.

**Comment by pkolaczk** [comment]
Fixed in 0.34
