### ISSUE TITLE
Compare with `fdupes`

### ISSUE THREAD

**Issue by piranna** [pkolaczk/fclones#25]
Add a compare with `fdupes`: performance, features...

**Comment by pkolaczk** [comment]
The benchmarks in README.md already include fdupes.
But why do you think comparing features would be useful?
I don't want to do this, because this could become very long and it can easily turn into "my program is better than yours" which I want to avoid. I listed the features of fclones in detail.

**Comment by piranna** [comment]
Sorry for the benchmarks, didn't see them before, really are impresive :+1: 

Competition is not bad if it allow for improvement. One of the things I mostly miss from `fdupes` is that's not possible to include as a library, while with Rust is fairly easy :-) My question was more about to compare what features does each one offer. For example, a feature I use a lot from `fdupes` is the option to delete files interactively, I don't see any flag for `fclones` to do so :-)

**Comment by pkolaczk** [comment]
That's right, fclones doesn't offer any way of deleting files automatically yet. I believe this is a task for a different program (or a subcommand) that would take output of fclones.

**Comment by piranna** [comment]
From a UNIX perspective, yes, it makes sense that task being done by another command, but being so much attached to fclones output format... :-/ Maybe a shell script wrapper that offer a compatible interface with fdupes? :-) That would be easy to implement, but not sure if It should be hosted here un fclones repo or being totally independent...

**Comment by aurelg** [comment]
Follow-up proposed in #27

**Comment by pkolaczk** [comment]
To wrap it up:
- Benchmarks are included in README
- I added the Limitations section to the README
Let me close this and leave #27 as
