### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by stav** [pkolaczk/fclones#273]
`fclones` finds my dupes and creates the output file:

	fclones group /run/media/stav/RYST/Legion/Pictures/DCIM >dupes.txt

	[2024-09-02 08:45:51.234] fclones:  info: Started grouping
	[2024-09-02 08:45:51.235] fclones:  info: Scanned 2961 file entries
	[2024-09-02 08:45:51.236] fclones:  info: Found 2958 (59.0 GB) files matching selection criteria
	[2024-09-02 08:45:51.237] fclones:  info: Found 1152 (24.2 GB) candidates after grouping by size
	[2024-09-02 08:45:51.237] fclones:  info: Found 1152 (24.2 GB) candidates after grouping by paths
	[2024-09-02 08:45:51.270] fclones:  info: Found 1152 (24.2 GB) candidates after grouping by prefix
	[2024-09-02 08:45:51.274] fclones:  info: Found 1152 (24.2 GB) candidates after grouping by suffix
	[2024-09-02 08:46:08.155] fclones:  info: Found 1152 (24.2 GB) redundant files

But the `move` command panics:

	RUST_BACKTRACE=1 fclones move . <dupes.txt 

	[2024-09-02 09:16:03.490] fclones:  info: Started deduplicating
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:                       ]             0 / 1152
	index out of bounds: the len is 0 but the index is 0
	stack backtrace:
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:281:thread '42<unnamed>:
	' panicked at index out of bounds: the len is 0 but the index is 0fclones/src/device.rs
	:281:42:
	index out of bounds: the len is 0 but the index is 0
	thread '<unnamed>' panicked at fclones/src/device.rs:thread '281<unnamed>thread ':' panicked at <unnamed>42fclones/src/device.rs' panicked at :
	:fclones/src/device.rsindex out of bounds: the len is 0 but the index is 0281:281
	::4242:
	:
	thread 'index out of bounds: the len is 0 but the index is 0index out of bounds: the len is 0 but the index is 0<unnamed>

	' panicked at fclones/src/device.rs:281:42:
	index out of bounds: the len is 0 but the index is 0
	   0: rust_begin_unwind
	             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
	   1: core::panicking::panic_fmt
	             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
	   2: core::panicking::panic_bounds_check
	             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:162:5
	   3: fclones::dedupe::dedupe::{{closure}}
	   4: <&rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
	   5: rayon::iter::plumbing::bridge_unindexed_producer_consumer
	   6: rayon_core::join::join_context::{{closure}}.6601
	   7: rayon::iter::plumbing::bridge_unindexed_producer_consumer
	   8: rayon_core::join::join_context::{{closure}}.6601
	   9: rayon::iter::plumbing::bridge_unindexed_producer_consumer
	  10: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
	  11: rayon_core::registry::WorkerThread::wait_until_cold
	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
	Aborted (core dumped)

**Comment by th1000s** [comment]
It seems it finds no devices, see [sysinfo v0.29.10, disk.rs:223](https://github.com/GuillaumeGomez/sysinfo/blob/v0.29.10/src/linux/disk.rs#L223) (the package which fclones relies on for the disk information). Note that `/run/media` is explicitly allowed by the filter condition `fs_file.starts_with("/run") && !fs_file.starts_with("/run/media")`.

Is this in a container or another sandboxed environment, or using an unusual filesystem? Is `cat /proc/mounts` (this is where sysinfo starts looking) listing  `/run/media` and other physical filesystems such as the root filesystem?

**Comment by stav** [comment]
Ah, I see that; so, I moved all the files to my home partition (Manjaro Arch Linux) and reran the `group` with generated a file like...

    # Report by fclones 0.34.0
    # Timestamp: 2024-09-12 16:07:11.957 -0400
    # Command: /snap/fclones/26/bin/fclones group DCIM
    # Base dir: /home/stav/Pictures/Legion
    # Total: 48424828564 B (48.4 GB) in 2304 files in 1152 groups
    # Redundant: 24212414282 B (24.2 GB) in 1152 files
    # Missing: 0 B (0 B) in 0 files
    24f943124897feb5093e5c08239ce569, 1166973200 B (1.2 GB) * 2:
        /home/stav/Pictures/Legion/DCIM/500-Camera/20230729_200900.mp4
        /home/stav/Pictures/Legion/DCIM/Camera Aug 2024/20230729_200900.mp4

But the `move` command still panics with the same message.

**Comment by th1000s** [comment]
I see it is installed via snap, the sandboxing probably hides some of the device info from fclones. Can you try running it without isolation, maybe copying the binary helps? Otherwise try a binary from the release page.

**Comment by stav** [comment]
Ok, I installed from official Arch repos and it worked!
