### ISSUE TITLE
Update README with a link to the AUR package for Archlinux

### ISSUE THREAD

**Issue by aurelg** [pkolaczk/fclones#28]
I just created an AUR package for Archlinux. You can find it here: https://aur.archlinux.org/packages/fclones-git/
It might be worth adding its name and a link to it in the README file.

**Comment by pkolaczk** [comment]
How can I make such packages by myself? I'm not using arch unfortunately, but is there any way to cross compile from ubuntu?

**Comment by aurelg** [comment]
With Arch, packages outside official repositories are usually distributed with AUR. All AUR requires is a PKGBUILD file providing instructions to download, build and create the Arch package locally. 

Here are links to:
- The [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines), you'll see that AUR can be used to provide binary packages as well.
- The [PKGBUILD I created](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fclones-git) to let other arch users build and create a package for fclones on their machines (the link to this PKGBUILD can be found on the fclones-git AUR page I posted above).

You can build the package wherever Docker runs, with the following Dockerfile:

```dockerfile
FROM archlinux:latest

# Update
RUN pacman --noconfirm -qSyu
RUN pacman --noconfirm -qS \
  base-devel \
  git

# Add and login as user makepkg, w/passwordless sudo
RUN useradd -G wheel -m makepkg
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
USER makepkg
WORKDIR /home/makepkg

# Build fclones-git package
RUN git clone https://aur.archlinux.org/fclones-git.git \
  && cd fclones-git \
  && makepkg -si --noconfirm
```
Then run the usual `docker build .`.


Should you have any question, just ask.

**Comment by pkolaczk** [comment]
I added the link to your package in README.md. 
Thank you!
