### ISSUE TITLE
Compiling to linux ARM

### ISSUE THREAD

**Issue by stuzenz** [pkolaczk/fclones#3]
Great work - already had a play with the utility on macos and it works great.

Just feedback, I also tried to compile to manjaro on the rpi4 and the compile failed on the hashing crate. I might ask the author o the fashhash-sys crate what would be required to allow it to compile on the arm architecture.

```
fclones git:(master) cargo build --release
   Compiling fasthash-sys v0.3.2
   Compiling getrandom v0.1.14
   Compiling num_cpus v1.13.0
   Compiling atty v0.2.14
error: failed to run custom build command for `fasthash-sys v0.3.2`

Caused by:
  process didn't exit successfully: `/home/stuart/rust_projects/fclones/target/release/build/fasthash-sys-3bfb9e86593b1584/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
CC_aarch64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wno-implicit-fallthrough" "-Wno-unknown-attributes" "-msse4.2" "-maes" "-mavx" "-mavx2" "-DT1HA0_RUNTIME_SELECT=1" "-DT1HA0_AESNI_AVAILABLE=1" "-Wall" "-Wextra" "-o" "/home/stuart/rust_projects/fclones/target/release/build/fasthash-sys-fc57bf495c3381b2/out/src/fasthash.o" "-c" "src/fasthash.cpp"
cargo:warning=cc: error: unrecognized command line option \u2018-msse4.2\u2019
cargo:warning=cc: error: unrecognized command line option \u2018-maes\u2019
cargo:warning=cc: error: unrecognized command line option \u2018-mavx\u2019
cargo:warning=cc: error: unrecognized command line option \u2018-mavx2\u2019
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wno-implicit-fallthrough" "-Wno-unknown-attributes" "-msse4.2" "-maes" "-mavx" "-mavx2" "-DT1HA0_RUNTIME_SELECT=1" "-DT1HA0_AESNI_AVAILABLE=1" "-Wall" "-Wextra" "-o" "/home/stuart/rust_projects/fclones/target/release/build/fasthash-sys-fc57bf495c3381b2/out/src/fasthash.o" "-c" "src/fasthash.cpp" with args "cc" did not execute successfully (status code exit code: 1).

', /home/stuart/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```
-- feel free to close this issue - I just wanted to give feedback.

**Comment by pkolaczk** [comment]
Thank you. Before closing, let me try a different hash crate. Maybe metrohash 128 would work?

**Comment by pkolaczk** [comment]
Let me know if it works now.

**Comment by pkolaczk** [comment]
I think it should be fine. The `metrohash` branch compiled for me with:
`cargo build --target=aarch64-unknown-linux-gnu`

**Comment by yehia2amer** [comment]
Hi @pkolaczk , Thanks for this Awesome tool.
I am new to rust, I tried to CrossCompile fclones using metrohash Branch for ARM Synology DS215j (CPU MARVELL Armada 375 88F6720) - target=armv7-unknown-linux-gnueabihf 

so I used this command: 
`cargo build --release --target=armv7-unknown-linux-gnueabihf --verbose`
but I am getting build error: https://gist.github.com/yehia2amer/e261114a78c2b8d758ef0ab1f0a36436

am I doing something wrong ?
Also any hope this could be part of [opkg ](https://openwrt.org/docs/guide-user/additional-software/opkg) package manager ?

Thanks again.

**Comment by pkolaczk** [comment]
Cargo is using a wrong linker. Add the following lines to `~/.cargo/config`

```
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```

**Comment by pkolaczk** [comment]
@yehia2amer @stuzenz 
I published cross-compiled binaries for aarch64 and armv7 - attached to the latest 0.2.0 release.
Please let me know if they work.

**Comment by stuzenz** [comment]
Hi again,

I really like fclones - and I have been learning rust, I am starting to try to grok parts of the source code - thanks again.

Thanks for all the effort on this issue. I went through your paths of thought above trying things on the Manjaro rpi4. Sadly, no success yet.

I will try again in the weekend and come back with some of the output from the shell.

I just downloaded the arm7 binary - and sadly it is failing. It is work noting that when I run the file it seems to be running the binary before failing with an output (there is a pause on hitting enter before the result.) The filesystem does acknowledge the file is there as I get no error message with chmod +x fclones (it was already an executable - but I did it anyway.

```
➜  dev ls -alh
total 7.3M
drwxr-xr-x  3 stuart stuart 4.0K Jun 19 06:39 .
drwx------ 33 stuart stuart 4.0K Jun 19 06:42 ..
-rwxrwxr-x  1 stuart stuart 5.5M Jun 19 06:39 fclones
-rw-r--r--  1 stuart stuart 1.9M Jun 19 05:48 fclones-0.3.0-linux.armv7.zip
drwxr-xr-x  2 stuart stuart 4.0K Jun 18 17:15 test
➜  dev ./fclones
zsh: no such file or directory: ./fclones
➜  dev
```

On a more positive note I managed to pull together a few simple commands on the macos system using the fclones report to dedupe my photo library (I plan on doing a few more checks before doing it against all my old archives of photos.

```
# Report all dupes	
fclones . -R > output.txt

# Inverse match of the size line and first match (I want to keep one copy)
pcregrep -M  -v ".*(GB|MB|KB|\d\sB)(.*\n\s\s\s\s.*)" output.txt > output1.txt

# Remove whitespace at beginning of the filepath
sed -e 's/^[ \t]*//' output1.txt > output2.txt

# Add double quotes
sed -i -e 's/^/"/' output2.txt
sed -i -e ’s/$/“/‘ output2.txt

# rm all dupes
cat output2.txt | xargs rm
```
cheers,
stu

**Comment by stuzenz** [comment]
Good news. I did a clean install of rust and rustup on the rpi4 (using yay package manager). The install succeeded (had failed in the past taking the curl route). 

I ran the following
```
cargo build --release
```
- and got success
```
➜  release git:(master) ./fclones
error: The following required arguments were not provided:
    <paths>...

USAGE:
    fclones <paths>... --format <format> --min-size <min-size> --threads <threads>

For more information try --help
➜  release git:(master) ./fclones --version
File Clones 0.3.0
➜  release git:(master)
```

Nice to have fclones on the system that is holding my backups. Thanks again!

Your cross compiled version didn't work for me, I don't know if there is any point, but let me know if you want me to provide my compiled version that at least works for manjaro rpi4 ARM.

Thanks again!

**Comment by yehia2amer** [comment]
> 
> 
> Cargo is using a wrong linker. Add the following lines to `~/.cargo/config`
> 
> ```
> [target.armv7-unknown-linux-gnueabihf]
> linker = "arm-linux-gnueabihf-gcc"
> ```

Thanks for the Quick Replay. I can confirm that it is working now after fixing the linker.
I will start testing the app and get back with feedback

Thanks again
