### ISSUE TITLE
Provide a Cargo.lock file

### ISSUE THREAD

**Issue by orhun** [pkolaczk/fclones#30]
You should commit the `Cargo.lock` file after building the project since it's a Rust binary. I suggest you to remove `Cargo.lock` line from [.gitignore#L3](https://github.com/pkolaczk/fclones/blob/master/.gitignore#L3)

For more information, please see: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by clbarnes** [comment]
This would help with future issues like #32 .
