### ISSUE TITLE
No binary releases

### ISSUE THREAD

**Issue by orhun** [pkolaczk/fclones#39]
Hey!

I'm maintaining [fclones](https://aur.archlinux.org/packages/fclones) and [fclones-bin](https://aur.archlinux.org/packages/fclones-bin) packages on AUR and I saw `0.9.0` release doesn't have binary artifacts. Unfortunately I couldn't bump the `-bin` package because of that.

Are you considering to bring back binary artifacts (e.g. `fclones-$pkgver.tgz`) along with the upcoming releases?

**Comment by pkolaczk** [comment]
Don't worry, they'll come today. I was a bit busy yesterday and something interrupted me finalizing the release.
