### ISSUE TITLE
Feat.req. GUI

### ISSUE THREAD

**Issue by necros2k7** [pkolaczk/fclones#49]
subj

**Comment by pkolaczk** [comment]
That's a great idea, but considering very limited amount of time I'm able to work on this project (this is a side project written for fun and learning) I'd like to focus more on the CLI/library part first. 

A GUI should be a separate crate using fclones as a library. I think it is not much work remaining to make fclones a good engine for a GUI app.

**Comment by pkolaczk** [comment]
The preview was merged in #207
