### ISSUE TITLE
Update benchmarks and add czkawka and rmlint  to comparsion

### ISSUE THREAD

**Issue by qarmin** [pkolaczk/fclones#52]
Hi,
I see that your app do some crazy optimizations for SSD and HDD, and I'm curious how fast it works in comparison to my app Czkawka(it use mostly simple optimizations and rather primitive algorighms, since I focus more on GUI).

I'm almost sure that with big amount of duplicated files fclones will be faster, but I'm curious if with second scan Czkawka will be faster due using caching hash results.

**Comment by pkolaczk** [comment]
Very quick one time comparison on my home folder (SSD).
Cold cache:
czkawka: 1:34.47
fclones 0:47.291

Hot cache (2nd run):
czkawka: 1:21.78
fclones: 0:18.996

Things I noticed:
1. czkawka has found fewer duplicates than fclones (~330k vs 372k). I did set the minimum size to 0 in czkawka to match fclones settings.
2. czkawka uses 100% of one core after displaying the results in the window

**Comment by pkolaczk** [comment]
After removing "excluded items", the timing of czkawka got worse: 1:52.83

BTW: Where does czkawka store the hash cache? 
I wonder if the fact that I have already run it some time ago didn't mess up the timings.

**Comment by qarmin** [comment]
~/.cache/czkawka - should contains cache from different types of tools

Also by default on Linux Czkawka don't show hardlinked files as duplicates(this can be disabled in settings)

**Comment by pkolaczk** [comment]
> Also by default on Linux Czkawka don't show hardlinked files as duplicates(this can be disabled in settings)

That's the same for `fclones`, unless option `-H` is given.

**Comment by pkolaczk** [comment]
Done as part of #56
