### ISSUE TITLE
--stdin Parameter Not Working

### ISSUE THREAD

**Issue by 9numbernine9** [pkolaczk/fclones#60]
Greetings!

I've been playing a bit with `fclones` this morning (super cool tool, BTW) and wanted to use the `--stdin` parameter to read the list of files to analyze from the output of `find`. Based on the documentation it seems like passing the input to `fclones group --stdin` should work, but whenever I try this I always get an error: `fclones: error: No input files`

Here's a simple, trivial example of what I mean:
```
localhost~ % fclones --version
fclones 0.12.2
localhost~ % mkdir blah
localhost~ % cd blah
localhost~/blah % touch {1,2,3}.c
localhost~/blah % find . -name '*.c'
./1.c
./2.c
./3.c
localhost~/blah % find . -name '*.c' | fclones group --stdin
[2021-06-19 15:01:12.126] fclones: error: No input files
```
I'm not sure if I'm doing something incorrectly - any ideas? Thanks in advance!

**Comment by pkolaczk** [comment]
Looks like a bug.

**Comment by pkolaczk** [comment]
I confirm, this is a bug, caused by incorrect error handling.

**Comment by 9numbernine9** [comment]
Works perfectly now - thanks for the quick fix @pkolaczk !
