### ISSUE TITLE
Feedback after inital testing

### ISSUE THREAD

**Issue by yehia2amer** [pkolaczk/fclones#7]
Hello @pkolaczk, Again Thanks a lot for this GREAT Tool. I do love the idea of parallel processing and using the power of rust in this tool! and I do have a couple of questions and maybe feature requests that I want to discuss with you.

So First of all, I Tested this tool on a low power DS215j NAS Device.
```
CPU: MARVELL Armada 375 88F6720 - Dual Core - 800 MHz (ARMv7)
RAM: 512 MB
HDD: 6TB WD NAS Drive
```

and those are my questions after testing:

### 1. Is There a way to Export the Report to a file instead of printing to the console?
This is useful when you have too much duplicates that the terminal window cannot handle. In my case I want to run the command on [Screen](https://www.gnu.org/software/screen/) and then come later to get the results.

I Tried the command below, but this don't give me any Progress/Status from the tool:
`sudo /usr/bin/time --verbose **./fclones ~ -R --format JSON** |& tee -a /volume2/duplicatesdata.json`

### 2. Can The Tool Add a timestamp to the status updates ?
This could be helpful to how much time each phase took, Something like:
```
2020-06-20T21:57:06 [INFO] - fclones:  info: Scanned 4687831 file entries
2020-06-21T05:57:06 [INFO] - fclones:  fclones:  info: Found 3857155 (5.4 TB) files matching selection criteria
2020-06-21T08:57:06 [INFO] - fclones:  fclones:  info: Found 3447623 (1.4 TB) candidates after grouping by size
```

### 3. Can The Tool have an option to persist the Analysis Data on a file/data-store, instead of RAM ?
In my Case The Device is slow & HDD is Big, Sometimes in other tools I need to run duplicate analysis for 6 days.
When I was trying this tool I lost power after leaving it running for 2 days. So this can help me run the tool again to continue analysis.

### 4. Can The Tool have an option to choose the Hashing algorithm ?
From what I can Seen in [here](https://github.com/rurban/smhasher) [Metrohash ](https://github.com/arthurprs/metrohash-rs) is a great hashing algorithm. but it is optimized for machine-specific (x64 SSE4.2) x86-64 architectures.
So Adding another algorithm that is not machine-specific would be a great addition.

**Comment by pkolaczk** [comment]
Thank you for the feedback! I'm happy the tool is helpful for you. Answers below:

1. Not yet, but this is trivial to implement. I thought stdout redirect (>) was enough, and I didn't think it composed badly with other tools like `time` in your case. 
2. Great idea and also very simple!
3. Do you mean saving metadata of intermediate stages to avoid hashing again? It would be definitely possible, but this one is a bit more work than the other ideas. 
4. Good idea - which algorithms would work the best for your use case?

**Comment by pkolaczk** [comment]
I created separate issues for each of your ideas
#8 #9 #10 #11 

Let's continue the conversation there.
