### ISSUE TITLE
Warning message confusing when physical file data location not available

### ISSUE THREAD

**Issue by paony** [pkolaczk/fclones#83]
I get the following messages running   fclones group yyy :

[2021-10-24 14:33:02.212] fclones:  warn: Failed to fetch extents for file <xxx>: Operation not supported (os error 95)

Maybe it's harmless, my problem is that I don't know what it means.
I am using version:   fclones 0.17.0
system is    xubuntu 20.04  (everything upgraded)
I run fclones on   aboaut 2TiB of data - 200000 files of all sizes 
filesystem is zfs (no mirror or raid but encrypted)
disk is spinning disk 4TiB

Warning occurs on 10 files of the 200000
Any ideas? Could the warning message be somewhat more verbose?
Can I just ignore it?

By the way - I have run a brief speed comparison on that data above - here are my results:
(Intel quad core - 16GB ram - disk cache fully loaded from previous operations)
fclones group  xxx                34 min
rdfind xxx                              81 min
jdupes -S -M -Q -r xxx          90 min
rmlint -T df xxx                     134 min
Pretty impresive!!!

**Comment by dsully** [comment]
This is happening for me with ZFS on Ubuntu 20.10 FWIW. Let me know if I can get any more information for you.

**Comment by pkolaczk** [comment]
I have everything I need. I need to change the message.

**Comment by paony** [comment]
Issue is clear for fclones then.

Might be an openZFS bug ...

Thanks for the quick reaction
