### ISSUE TITLE
Can't compile on FreeBSD

### ISSUE THREAD

**Issue by timothywinters** [pkolaczk/fclones#85]
Tried to compile from source on a FreeBSD jail, got these errors, tried again with the verbose flag to get more information.

   Compiling fclones v0.17.0

error[E0063]: missing field `l_sysid` in initializer of `flock`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fclones-0.17.0/src/lock.rs:31:17
   |
31 |         let f = libc::flock {
   |                 ^^^^^^^^^^^ missing `l_sysid`

error[E0063]: missing field `l_sysid` in initializer of `flock`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fclones-0.17.0/src/lock.rs:47:17
   |
47 |         let f = libc::flock {
   |                 ^^^^^^^^^^^ missing `l_sysid`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0063`.
error: failed to compile `fclones v0.17.0`, intermediate artifacts can be foundat `/tmp/cargo-installPdO1Nf`

Caused by:
  could not compile `fclones`

See attached file for full message. 
[FreeBSD fclones Errors.docx](https://github.com/pkolaczk/fclones/files/7425119/FreeBSD.fclones.Errors.docx)

**Comment by pkolaczk** [comment]
Should be fine now, but I have no way to test (no freebsd setup anywhere). Can you check if it works for you and if so, I'll cut the next release?

**Comment by timothywinters** [comment]
Tried compiling that branch, got the same errors. You could try running a version of freeBSD in a virtual machine or container of some variety to test it directly.

**Comment by pkolaczk** [comment]
"got the same errors." That's not possible, because those lines are not present.
