### ISSUE TITLE
isolate behavior removes dupes same volume

### ISSUE THREAD

**Issue by mlybarger** [pkolaczk/fclones#97]
when using --isolate for two directories, duplicate files within the directories are also being deleted. my understanding is the files w/i the volumes aren't considered for duplicate removal.

`  
cd /mnt/media
mkdir test-a
mkdir test-b
echo "test-one" > test-a/test-1
echo "test-one" > test-a/test-2
echo "test-one" > test-b/test-1
echo "test-one" > test-b/test-2
echo "test-two" > test-a/test-3
echo "test-two" > test-a/test-4
echo "test-two" > test-b/test-4
fclones group --isolate /mnt/media/test-a /mnt/media/test-b > test.txt
fclones remove --dry-run <test.txt 
[2022-02-15 12:53:15.823] fclones:  info: Started deduplicating (dry run)
rm /mnt/media/test-a/test-4
rm /mnt/media/test-a/test-2
rm /mnt/media/test-b/test-4
rm /mnt/media/test-b/test-1
rm /mnt/media/test-b/test-2
[2022-02-15 12:53:15.826] fclones:  info: Would process 5 files and reclaim 45 B space

`

**Comment by pkolaczk** [comment]
The --isolate option makes duplicate files within the same root counted as one. But in this case you have same files under different roots, so they are properly treated as duplicates.

**Comment by pkolaczk** [comment]
After thinking about it a bit more, indeed I think the removal behaviour is wrong. It should only remove files from one root in this case and leave the other root untouched.

**Comment by pkolaczk** [comment]
Still not perfect, because reporting of the number of files to be removed in the report is wrong.

**Comment by pkolaczk** [comment]
Closing this and created a separate issue #99
